version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0

    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests! ppp
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Deploy Master it pto Heroku
          command: |
            git push https://heroku:$ops200-deliveritwell@git.heroku.com/$ops200-deliveritwell.git main
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main  
